### ISSUE TITLE
ToDo: Junk check

### ISSUE THREAD

**Issue by lukbukkit** [LukWebsForge/JustMail#5]
- [ ] Reverse DNS
- [ ] [DKIM ](http://www.dkim.org) (Min. 1024 Bits)
- [ ] [SPF](http://www.openspf.org/)
- [ ] [DMARC](https://dmarc.org/)
- [ ] Compare header atrributes and the from and to attributes
