### ISSUE TITLE
ToDo: Outgoing mail support

### ISSUE THREAD

**Issue by lukbukkit** [LukWebsForge/JustMail#6]
- [ ] Relay mails to other servers if the user is authenticated
- [ ] Add the return-path
- [ ] Add a signature for the domain. See #5
